# Generated by Django 5.2.1 on 2025-05-16 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_payments_payment_link_payments_payment_session_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='status',
        ),
    ]
